"""Build data.js from the pokemondb.net extracts in this folder.

moves.txt       Name|type|power|category[|c]   (c = always crits)
pokemon_raw.txt Label|dex|types                (one entry per distinct typing per species)
Type letters: a..r = Normal Fire Water Electric Grass Ice Fighting Poison Ground
Flying Psychic Bug Rock Ghost Dragon Dark Steel Fairy
"""
import json, pathlib
here = pathlib.Path(__file__).parent
SPECIES = {128:"Tauros",351:"Castform",386:"Deoxys",412:"Burmy",413:"Wormadam",487:"Giratina",
 492:"Shaymin",550:"Basculin",555:"Darmanitan",641:"Tornadus",642:"Thundurus",645:"Landorus",
 647:"Keldeo",648:"Meloetta",678:"Meowstic",681:"Aegislash",710:"Pumpkaboo",711:"Gourgeist",
 718:"Zygarde",741:"Oricorio",745:"Lycanroc",746:"Wishiwashi",774:"Minior",849:"Toxtricity",
 875:"Eiscue",876:"Indeedee",877:"Morpeko",888:"Zacian",889:"Zamazenta",892:"Urshifu",
 898:"Calyrex",902:"Basculegion",905:"Enamorus",916:"Oinkologne",925:"Maushold",931:"Squawkabilly",
 964:"Palafin",978:"Tatsugiri",982:"Dudunsparce",999:"Gimmighoul",1017:"Ogerpon",1024:"Terapagos"}
moves = []
for e in (here/"moves.txt").read_text().strip().split(";"):
    p = e.split("|")
    moves.append([p[0], p[1], int(p[2]), p[3], 1 if len(p) > 4 else 0])
multi = {}
for line in (here/"multihit.txt").read_text(encoding="utf-8").splitlines():
    if not line.strip() or line.startswith("#"):
        continue
    name, factor, label = line.split("|", 2)
    multi[name] = [float(factor), label]
names = {m[0] for m in moves}
missing = set(multi) - names
assert not missing, f"multihit.txt names not in moves.txt: {missing}"
for m in moves:
    if m[0] in multi:
        m.extend(multi[m[0]])
mons = []
for e in (here/"pokemon_raw.txt").read_text().strip().split(";"):
    label, num, types = e.split("|")
    sp = SPECIES.get(int(num))
    if sp and label != sp:
        label = f"{sp} ({label})"
    mons.append([label, int(num), types])
items = []
for line in (here/"items.txt").read_text(encoding="utf-8").splitlines():
    if not line.strip() or line.startswith("#"):
        continue
    name, kind, arg, mult, effect = line.split("|", 4)
    items.append([name, kind, arg, float(mult), effect])
out = "// Generated by data/build_data.py from pokemondb.net (moves: /move/all, Pokémon: /pokedex/all, items: /item/all)\n"
out += "window.RM_DATA = " + json.dumps({"moves": moves, "mons": mons, "items": items}, ensure_ascii=False, separators=(",", ":")) + ";\n"
(here.parent/"data.js").write_text(out, encoding="utf-8")
print(len(moves), "moves,", len(mons), "pokemon,", len(items), "items")
